account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from .forms import (UserLoginForm,PwdResetForm,PwdResetConfirmForm)

from . import views

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html/',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
                                                                                                name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
#     # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

basket/urls.py
from django.urls import path
from  . import views

app_name='basket'

urlpatterns=[
    path('',views.basket_summary ,name='basket_summary'),
    path('add/',views.basket_add ,name='basket_add'),
    path('delete/',views.basket_delete ,name='basket_delete'),
    path('update/',views.basket_update ,name='basket_update'),



    ]

e_app/urls.py
from django.urls import path

from . import views

app_name='e_app'
urlpatterns=[
    path('',views.all_products,name="all_products"),
    path('<slug:slug>',views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/',views.category, name='category_list'),

]

e_comm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_app.urls' ,namespace='e_app')),
    path('basket/', include('basket.urls' ,namespace='basket')),
    path('account/', include('account.urls' ,namespace='account')),
    path('payment/', include('payment.urls' ,namespace='payment')),
    path('orders/', include('orders.urls' ,namespace='orders')),



]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from .basket import Basket
from e_app.models import Product
# Create your views here.

def basket_summary(request):
    basket = Basket(request)
    return render(request, 'basket.html', {'basket':basket})

def basket_add(request):
    basket= Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty':basketqty})
        return response
    
def basket_delete(request):
    basket= Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))  
        basket.delete(product=product_id)
        basketqty = basket.__len__()

        baskettotal= basket.get_total_price()
        response = JsonResponse({'qty':basketqty, 'subtotal':baskettotal})
        return response
    
def basket_update(request):
    basket= Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))  
        product_qty = int(request.POST.get('productqty'))  
        basket.update(product=product_id,qty=product_qty)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty':basketqty, 'subtotal':baskettotal})
        return response

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Eflyer</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'hm/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'hm/css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'hm/css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'hm/images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'hm/css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <!--  -->
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'hm/css/owl.carousel.min.css' %}">
      <link rel="stylesoeet" href="{% static 'hm/css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
   
   </head>
   <body>
      <!-- banner bg main start -->
      <div class="banner_bg_main">
         <!-- header top section start -->
         <div class="container">
            <div class="header_section_top">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="custom_menu">
                        <ul>
                           <li><a href="#">Best Sellers</a></li>
                           <li><a href="#">Gift Ideas</a></li>
                           <li><a href="#">New Releases</a></li>
                           <li><a href="#">Today's Deals</a></li>
                           <li><a href="#">Customer Service</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header top section start -->
         <!-- logo section start -->
         <div class="logo_section">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="logo"><a href="/"><img src="{% static 'hm/images/logo.png' %}"></a></div>
                  </div>
               </div>
            </div>
         </div>
         <!-- logo section end -->
         <!-- header section start -->
         <div class="header_section">
            <div class="container">
               <div class="containt_main">
                  <div id="mySidenav" class="sidenav">
                     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                     <a href="{% url "e_app:all_products" %}">Home</a>
                     {% for c in categories %}
                     <a href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                     {% endfor %}
                     <!-- <a href="electronic.html">Electronic</a>
                     <a href="jewellery.html">Jewellery</a> -->
                  </div>
                  <span class="toggle_icon" onclick="openNav()"><img src="{% static 'hm/images/toggle-icon.png' %}"></span>
                  <div class="dropdown">
                     <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category
                     </button>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url "e_app:all_products" %}">All</a>

                        {% for c in categories %}
                        <li {% if category.sulg == c.slug %}class="selected" {% endif %}></li>
                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                        {% endfor %}
                        
                        <!-- <a class="dropdown-item" href="#">Something else here</a> -->
                     </div>
                  </div>
                  <div class="main">
                     <!-- Another variation with a button -->

                     
                        <div class="input-group">
                           <input type="text" class="form-control" placeholder="Search ..." >
                           <div class="input-group-append">
                              <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                              <i class="fa fa-search"></i>
                              </button>
                           </div>
                        </div>
                    
                  </div>
                  <div class="header_box">
                     <!-- <div class="lang_box ">
                        <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                        <img src="{% static 'hm/images/flag-uk.png' %}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu ">
                           <a href="#" class="dropdown-item">
                           <img src="{% static 'hm/images/flag-france.png' %}" class="mr-2" alt="flag">
                           French
                           </a>
                        </div>
                     </div> -->
                     <div class="login_menu">
                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="d-inline-flex">
                           {% if total_qty > 0 %}
                              {{ total_qty }}
                           {% else %}
                              0
                           {% endif %}
                        </div>
                        {% endwith %}
                        <ul>
                           
                           <li><a href="{% url "basket:basket_summary" %}">
                              
                              <i class="fa fa-shopping-cart" aria-hidden="true"></i>

                              <span class="padding_10">Cart</span></a>
                           </li>
                           {% if user.is_authenticated %}
                           <li><a href="{% url "account:logout" %}">
                              <i class="fa fa-user" aria-hidden="true"></i>
                              <span class="padding_10">logout</span></a>
                           </li>
                           {% else %}
                           <li><a href="{% url "account:login" %}">
                              <i class="fa fa-user" aria-hidden="true"></i>
                              <span class="padding_10">login</span></a>
                           </li>
                           {% endif %}

                           <li><a href="{% url 'account:dashboard' %}">
                              <i class="fa fa-user" aria-hidden="true"></i>
                              <span class="padding_10">Account</span></a>
                           </li>


                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header section end -->
         <!-- banner section start -->
         <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="{% url "account:register" %}">join us</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital"> create <br>an account</h1>
                              <div class="buynow_bt"><a href="{% url "account:register" %}">join us</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">quality <br>product</h1>
                              <div class="buynow_bt"><a href="{% url "account:register" %}">join us</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->
      </div>
      <!-- banner bg main end -->
      <!-- fashion section start -->
      
      {% block content %}
      
      {% endblock %}

      <!-- f end -->
      <!-- electronic section start -->

      <!-- electronic section end -->
      <!-- jewellery  section start -->
      
      <!-- jewellery  section end -->
      <!-- footer section start -->
      <div class="footer_section layout_padding">
         <div class="container">
            <div class="footer_logo"><a href="index.html"><img src="{% static 'hm/images/footer-logo.png' %}"></a></div>
            <div class="input_bt">
               <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
               <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
            </div>
            <div class="footer_menu">
               <ul>
                  <li><a href="#">Best Sellers</a></li>
                  <li><a href="#">Gift Ideas</a></li>
                  <li><a href="#">New Releases</a></li>
                  <li><a href="#">Today's Deals</a></li>
                  <li><a href="#">Customer Service</a></li>
               </ul>
            </div>
            <div class="location_main">Help Line  Number : <a href="#">+1 1800 1200 1200</a></div>
         </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'hm/js/jquery.min.js' %}"></script>
      <script src="{% static 'hm/js/popper.min.js' %}"></script>
      <script src="{% static 'hm/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'hm/js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'hm/js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'hm/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'hm/js/custom.js' %}"></script>
      <script>
         function openNav() {
           document.getElementById("mySidenav").style.width = "250px";
         }

         function closeNav() {
           document.getElementById("mySidenav").style.width = "0";
         }
      </script>
   </body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- {%if category %}{{category.name|title}}{% else %}Products{% endif %} -->

<div>
    <p class="fashion_taital">{{ category.name|title }}</p>

</div>
<div class="fashion_section_2">
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4 col-sm-4">
            <div class="box_main">
                <h4 class="shirt_text">{{product.title}}</h4>
                <p class="price_text">Price <span style="color: #262626;">{{product.price}}</span></p>
                <div class="tshirt_img"><img src="{{ product.image.url }}"></div>
                <div class="btn_main">
                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                    <div class="seemore_bt"><a href="{{ product.get_absolute_url }}">See More</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1 class="fashion_taital">Man & Woman Fashion</h1>

        <div class="fashion_section_2">
           <div class="row">
              {% for pr in products %}

              <div class="col-lg-4 col-sm-4">

                 <div class="box_main">

                    <h4 class="shirt_text">{{pr.title}}</h4>
                    <p class="price_text">Price <span style="color: #262626;">{{pr.price}}</span></p>
                    <div class="tshirt_img"><img src="{{ pr.image.url }}"></div>
                    <div class="btn_main">
                       <div class="buy_bt"><a href="#">Buy Now</a></div>
                       <div class="seemore_bt"><a href="{{ pr.get_absolute_url }}">See More</a></div>
                    </div>

                 </div>
              </div>
              {% endfor %}


              
           </div>
        </div>


     </div>

</body>
</html>

templates/singles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Fashion</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{% static 'hm/css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{% static 'hm/css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{% static 'hm/css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{% static 'hm/images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{% static 'hm/css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
   <!-- font awesome -->
   <link rel="stylesheet" type="text/css"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <!--  -->
   <!-- owl stylesheets -->
   <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext"
      rel="stylesheet">
   <link rel="stylesheet" href="{% static 'hm/css/owl.carousel.min.css' %}">
   <link rel="stylesoeet" href="{% static 'hm/css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">

   <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
</head>

<body>
   <div class="container">

      <div class="fashion_section_2">
         <div class="row">


            <div class="container">
               <main class="pt-5">
                  <div class="row g-3">
                     <div class="col-md-5 col-lg-5 order-md-first bg-light">
                        <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                           src="{{ product.image.url }}">

                     </div>
                     <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                        <h1 class="md-0 h4">{{product.title}}</h1>
                        <p><span class="lead">{{product.author}}</span>(company)</p>
                        <p>{{product.desc}}</p>
                        <div class="border">
                           <div class="col border-bottom">
                              <div class="row p-3">
                                 <div class="col-6">orginal product</div>

                                 <div class="col-6 text-end"><span class="h4 fw-bold">$ {{ product.price }}</span>
                                 </div>

                                 <div class="container">
                                    <div class="col-6">
                                       <label for="select">Qty</label>
                                       <select id="select">
                                          <option value="1">1</option>
                                          <option value="2">2</option>
                                          <option value="3">3</option>
                                          <option value="4">4</option>
                                          <option value="5">5</option>

                                       </select>

                                    </div>


                                    <!-- <a href="" class="tm-btn tm-btn-1 tm-link-to-services">ADD to cart</a> -->
                                    <button type="button" id="add-button" value="{{product.id}}"
                                       class="btn btn-secondary btn-sm">
                                       ADD to cart

                                    </button>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </main>
            </div>
         </div>
      </div>
   </div>

   <script>
      $(document).on('click', '#add-button', function (e) {
         e.preventDefault();
         console.log($('#select option:selected').text())
         $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
               productid: $('#add-button').val(),
               productqty: $('#select option:selected').text(),
               csrfmiddlewaretoken: "{{csrf_token}}",
               action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty

            },
            error: function (xhr, errmsg, err) {}
         });

      })
   </script>
</body>

</html>
{% endblock %}